{
  "openapi": "3.0.0",
  "info": {
    "title": "EXPRESS-SERVER",
    "version": "1.0.0",
    "description": "RESTFUL API DENGAN EXPRESS JS DAN MONGO DB"
  },
  "paths": {
    "openapi": {
      "0": "3",
      "1": ".",
      "2": "0",
      "3": ".",
      "4": "0"
    },
    "info": {
      "title": "EXPRESS-SERVER",
      "version": "1.0.0",
      "description": "RESTFUL API DENGAN EXPRESS JS DAN MONGO DB"
    }
  },
  "components": {},
  "tags": []
}